### ISSUE TITLE
Cancelamento automático do download

### ISSUE THREAD

**Issue by brnleonel** [brunoxkk0/BethaLogs#1]
Incluir esse código no arquivo **[downloadHandler.js](https://github.com/brunoxkk0/BethaLogs/blob/master/downloadHandler.js)** para cancelamento automático do download após a leitura do log.

```
chrome.downloads.onDeterminingFilename.addListener(async (downloadItem) => {
    if (downloadItem.finalUrl.includes("logs/logs.txt.gz")) {
        chrome.downloads.cancel(downloadItem.id, () => {
            console.log("Download cancelado...")
        })
    }
})
```

**Comment by brunoxkk0** [comment]
Você diz no sentido de mover a lógica para fora do onCreated e colocar no onDeterminingFilename ?

**Comment by brnleonel** [comment]
> Você não faz sentido de mover a lógica para fora do onCreated e colocar no onDeterminingFilename ?

Não, somente adicionar esse novo ao final do código, assim ele cancela o download sem abrir nenhum pop-up!
Meu Chrome esta habilitado para perguntar onde salvar o arquivo, com esse código eu não preciso cancelar o download do arquivo manualmente.

**Comment by brunoxkk0** [comment]
Pelo que testei aqui, funcionou legal. testa a release que o GitHub gerou pra ver se ficou certo.
